### ISSUE TITLE
Version error

### ISSUE THREAD

**Issue by Laura7089** [hanmertens/pstoedit-rs#1]
The library is returning an "incompatible version" error with `pstoedit` 4.0 on linux; the README seems to imply this is supported.

**Comment by hanmertens** [comment]
The library is currently incompatible with pstoedit 4.00. This version didn't exist yet when I wrote the README; I've updated it to reflect the incompatibility in 0bcd7d6d6f4fa24c11f95689065492baab28cb1d.
